spring:
  # ensure that objects returned do not include null
  jackson:
    default-property-inclusion: non_null
  # openfeign configurations
  cloud:
    openfeign:
      oauth2:
        enabled: true
        clientRegistrationId: twitch
      client:
        config:
          twitch-api:
            url: https://api.twitch.tv/helix
            loggerLevel: basic
            default-request-headers:
              Client-Id: "aspgmiydr5du7jqfxmfo4xqy9oxx3f"
  # set up authentication with openfeign -> twitch
  security:
    oauth2:
      client:
        registration:
          twitch:
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_post
            client-id: "aspgmiydr5du7jqfxmfo4xqy9oxx3f"
            client-secret: "m7c1893rksq2d2vntzji8ccs3hohp2"
        provider:
          twitch:
            token-uri: https://id.twitch.tv/oauth2/token

# log HTTP console with a TRACE level/priority
logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: TRACE # Incoming http requests
    com.ericqiu.twitch.external.TwitchApiClient: DEBUG
